# Generated by Django 5.2.4 on 2025-07-25 21:10

import datetime
import django.db.models.deletion
import registros.models.validators
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tipo_suelo', models.CharField(max_length=100, verbose_name='Tipo de Suelo')),
                ('distancia', models.CharField(max_length=100, verbose_name='Distancia')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Registro Acceso',
                'verbose_name_plural': 'Registros Acceso',
            },
        ),
        migrations.CreateModel(
            name='RegTxtss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='REmpalme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('lat', models.FloatField(blank=True, null=True, validators=[registros.models.validators.validar_latitud], verbose_name='Latitud Empalme')),
                ('lon', models.FloatField(blank=True, null=True, validators=[registros.models.validators.validar_longitud], verbose_name='Longitud Empalme')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor')),
                ('capacidad', models.CharField(max_length=100, verbose_name='Capacidad')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Registro Empalme',
                'verbose_name_plural': 'Registros Empalme',
            },
        ),
        migrations.CreateModel(
            name='RSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('lat', models.FloatField(validators=[registros.models.validators.validar_latitud], verbose_name='Latitud Inspeccion')),
                ('lon', models.FloatField(validators=[registros.models.validators.validar_longitud], verbose_name='Longitud Inspeccion')),
                ('altura', models.CharField(max_length=100, verbose_name='Altura Torre')),
                ('dimensiones', models.CharField(max_length=100, verbose_name='Dimensiones del Sitio')),
                ('deslindes', models.CharField(max_length=100, verbose_name='Deslindes')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Registro Sitio',
                'verbose_name_plural': 'Registros Sitio',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegTxtss',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sitio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.site', verbose_name='Sitio')),
            ],
            options={
                'verbose_name': 'historical reg txtss',
                'verbose_name_plural': 'historical reg txtsss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
