# Generated by Django 5.2.4 on 2025-07-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_txtss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregtxtss',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='racceso',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='regtxtss',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='rempalme',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='rsitio',
            name='deleted_at',
        ),
    ]
