# Generated by Django 5.2.3 on 2025-09-03 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('reg_txtss', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregtxtss',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalregtxtss',
            name='sitio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.site', verbose_name='Sitio'),
        ),
        migrations.AddField(
            model_name='historicalregtxtss',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='regtxtss',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_txtss', to='core.site', verbose_name='Sitio'),
        ),
        migrations.AddField(
            model_name='regtxtss',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_txtss', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='racceso',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_txtss.regtxtss', verbose_name='Registro'),
        ),
        migrations.AddField(
            model_name='rempalme',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_txtss.regtxtss', verbose_name='Registro'),
        ),
        migrations.AddField(
            model_name='rsitio',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_txtss.regtxtss', verbose_name='Registro'),
        ),
    ]
