# Generated by Django 5.2.4 on 2025-07-22 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_txtss', '0003_rsitio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsitio',
            name='name',
        ),
    ]
