# Generated by Django 5.2.4 on 2025-07-23 03:38

import registros.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_txtss', '0004_remove_rsitio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rempalme',
            name='lat',
            field=models.FloatField(blank=True, null=True, validators=[registros.models.validators.validar_latitud], verbose_name='Latitud Empalme'),
        ),
        migrations.AddField(
            model_name='rempalme',
            name='lon',
            field=models.FloatField(blank=True, null=True, validators=[registros.models.validators.validar_longitud], verbose_name='Longitud Empalme'),
        ),
    ]
