# Generated by Django 5.2.4 on 2025-07-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_txtss', '0005_rempalme_lat_rempalme_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsitio',
            name='deslindes',
            field=models.CharField(max_length=100, verbose_name='Deslindes'),
        ),
        migrations.AlterField(
            model_name='rsitio',
            name='dimensiones',
            field=models.CharField(max_length=100, verbose_name='Dimensiones del Sitio'),
        ),
    ]
