# Generated by Django 5.2.4 on 2025-07-25 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_txtss', '0006_alter_rsitio_deslindes_alter_rsitio_dimensiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregtxtss',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='regtxtss',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de registro'),
        ),
    ]
