# Generated by Django 5.2.3 on 2025-08-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentegrupo',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='componentegrupo',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
