# Generated by Django 5.2.3 on 2025-09-03 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoComponentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidencia', models.DecimalField(decimal_places=2, help_text='En porcentaje, debe sumar 100% entre todos los componentes del grupo.', max_digits=5)),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.componente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='proyectos.grupocomponentes')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'unique_together': {('grupo', 'componente')},
            },
        ),
    ]
