# Generated by Django 5.2.3 on 2025-09-03 22:40

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('app_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Aplicación')),
                ('google_maps_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Maps API Key')),
                ('logo', models.FileField(blank=True, null=True, upload_to='app_settings/logo/', verbose_name='logo')),
                ('recipients_email', models.TextField(blank=True, null=True, verbose_name='Correo de destinatarios')),
                ('app_apk', models.FileField(blank=True, null=True, upload_to='app_settings/apk/', verbose_name='APK de la Aplicación')),
                ('last_apk_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Última versión del APK')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del contratista', max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código único del contratista', max_length=50, unique=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el contratista está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': 'Contratistas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContractor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del contratista', max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(db_index=True, help_text='Código único del contratista', max_length=50, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el contratista está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Contratista',
                'verbose_name_plural': 'historical Contratistas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSite',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pti_cell_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='PTI ID')),
                ('operator_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nombre del sitio')),
                ('lat_base', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Latitud Mandato')),
                ('lon_base', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Longitud Mandato')),
                ('alt', models.IntegerField(blank=True, null=True, verbose_name='Altura (m)')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Región')),
                ('comuna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna')),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Sitio',
                'verbose_name_plural': 'historical Sitios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pti_cell_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='PTI ID')),
                ('operator_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del sitio')),
                ('lat_base', models.FloatField(blank=True, null=True, unique=True, verbose_name='Latitud Mandato')),
                ('lon_base', models.FloatField(blank=True, null=True, unique=True, verbose_name='Longitud Mandato')),
                ('alt', models.IntegerField(blank=True, null=True, verbose_name='Altura (m)')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Región')),
                ('comuna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitios',
                'ordering': ['pti_cell_id'],
            },
        ),
        migrations.CreateModel(
            name='GoogleMapsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('etapa', models.CharField(max_length=100, verbose_name='Etapa del registro')),
                ('zoom', models.IntegerField(verbose_name='Nivel de zoom')),
                ('maptype', models.CharField(default='hybrid', max_length=50, verbose_name='Tipo de mapa')),
                ('scale', models.IntegerField(default=2, verbose_name='Escala')),
                ('tamano', models.CharField(default='1200x600', max_length=20, verbose_name='Tamaño')),
                ('imagen', models.ImageField(help_text='Imagen estática generada por Google Maps API', upload_to='google_maps/', verbose_name='Imagen del mapa')),
                ('coordenadas_json', models.TextField(help_text='Coordenadas utilizadas para generar el mapa', verbose_name='Coordenadas JSON')),
                ('distancia_total_metros', models.FloatField(blank=True, null=True, verbose_name='Distancia total (metros)')),
                ('desfase_metros', models.FloatField(blank=True, null=True, verbose_name='Desfase (metros)')),
                ('was_created', models.BooleanField(default=True, help_text='Indica si la imagen fue creada o ya existía', verbose_name='Fue creado')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Imagen de Google Maps',
                'verbose_name_plural': 'Imágenes de Google Maps',
                'ordering': ['-created_at'],
            },
        ),
    ]
