# Generated by Django 5.2.3 on 2025-07-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
