# Generated by Django 5.2.3 on 2025-08-12 22:55

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contratista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del contratista', max_length=200, verbose_name='Nombre')),
                ('rut', models.CharField(help_text='RUT del contratista (formato: XX.XXX.XXX-X)', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato XX.XXX.XXX-X', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$')], verbose_name='RUT')),
                ('email', models.EmailField(blank=True, help_text='Email de contacto del contratista', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Teléfono de contacto del contratista', max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, help_text='Dirección del contratista', null=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el contratista está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': 'Contratistas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContractor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del contratista', max_length=200, verbose_name='Nombre')),
                ('rut', models.CharField(db_index=True, help_text='RUT del contratista (formato: XX.XXX.XXX-X)', max_length=12, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato XX.XXX.XXX-X', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$')], verbose_name='RUT')),
                ('email', models.EmailField(blank=True, help_text='Email de contacto del contratista', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Teléfono de contacto del contratista', max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, help_text='Dirección del contratista', null=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el contratista está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Contratista',
                'verbose_name_plural': 'historical Contratistas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
