# Generated by Django 5.2.3 on 2025-07-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalsite_user_site_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['pti_cell_id'], 'verbose_name': 'Sitio', 'verbose_name_plural': 'Sitios'},
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='site',
            name='user',
        ),
    ]
