# Generated by Django 5.2.3 on 2025-09-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='parent_app_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de la aplicación padre'),
        ),
    ]
