# Generated by Django 5.2.3 on 2025-08-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contractor_historicalcontractor'),
        ('reg_construccion', '0006_remove_historicalregconstruccion_contratista_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contratista',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='historicalcontractor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalcontractor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalcontractor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='historicalcontractor',
            name='rut',
        ),
        migrations.AddField(
            model_name='contractor',
            name='code',
            field=models.CharField(default=1, help_text='Código único del contratista', max_length=50, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontractor',
            name='code',
            field=models.CharField(db_index=True, default=1, help_text='Código único del contratista', max_length=50, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(help_text='Nombre del contratista', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalcontractor',
            name='name',
            field=models.CharField(help_text='Nombre del contratista', max_length=200, verbose_name='Nombre'),
        ),
    ]
