# Generated by Django 5.2.3 on 2025-07-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsite',
            name='alt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alt. (m)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='alt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alt. (m)'),
        ),
    ]
