# Generated by Django 5.2.3 on 2025-07-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_historicalsite_alt_alter_site_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('app_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Aplicación')),
                ('google_maps_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Maps API Key')),
                ('logo', models.FileField(blank=True, null=True, upload_to='app_settings/logo/', verbose_name='logo')),
                ('recipients_email', models.TextField(blank=True, null=True, verbose_name='Correo de destinatarios')),
                ('app_apk', models.FileField(blank=True, null=True, upload_to='app_settings/apk/', verbose_name='APK de la Aplicación')),
                ('last_apk_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Última versión del APK')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
