# Generated by Django 5.2.4 on 2025-07-22 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_remove_appsettings_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMapsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('etapa', models.CharField(max_length=100, verbose_name='Etapa del registro')),
                ('zoom', models.IntegerField(verbose_name='Nivel de zoom')),
                ('maptype', models.CharField(default='hybrid', max_length=50, verbose_name='Tipo de mapa')),
                ('scale', models.IntegerField(default=2, verbose_name='Escala')),
                ('tamano', models.CharField(default='1200x600', max_length=20, verbose_name='Tamaño')),
                ('imagen', models.ImageField(help_text='Imagen estática generada por Google Maps API', upload_to='google_maps/', verbose_name='Imagen del mapa')),
                ('coordenadas_json', models.TextField(help_text='Coordenadas utilizadas para generar el mapa', verbose_name='Coordenadas JSON')),
                ('distancia_total_metros', models.FloatField(blank=True, null=True, verbose_name='Distancia total (metros)')),
                ('desfase_metros', models.FloatField(blank=True, null=True, verbose_name='Desfase (metros)')),
                ('was_created', models.BooleanField(default=True, help_text='Indica si la imagen fue creada o ya existía', verbose_name='Fue creado')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Imagen de Google Maps',
                'verbose_name_plural': 'Imágenes de Google Maps',
                'ordering': ['-created_at'],
                'unique_together': {('content_type', 'object_id', 'etapa')},
            },
        ),
    ]
