# Generated by Django 5.2.3 on 2025-08-07 16:23

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegConstruccion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estructura', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyectos.grupocomponentes', verbose_name='Estructura')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sitio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.site', verbose_name='Sitio')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical reg construccion',
                'verbose_name_plural': 'historical reg construccions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RegConstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estructura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_construccion', to='proyectos.grupocomponentes', verbose_name='Estructura')),
                ('sitio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_construccion', to='core.site', verbose_name='Sitio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_construccion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha del avance')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('porcentaje_avance', models.IntegerField(default=0, help_text='Porcentaje de avance del 0 al 100', verbose_name='Porcentaje de avance')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_construccion.regconstruccion', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Registro Avance',
                'verbose_name_plural': 'Registros Avance',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_construccion.regconstruccion', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Registro Visita',
                'verbose_name_plural': 'Registros Visita',
            },
        ),
        migrations.CreateModel(
            name='EjecucionPorcentajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_ejec_actual', models.DecimalField(decimal_places=2, help_text='Porcentaje de ejecución actual del componente', max_digits=5, verbose_name='Porcentaje Ejecución Actual')),
                ('porcentaje_ejec_anterior', models.DecimalField(decimal_places=2, help_text='Porcentaje de ejecución anterior del componente', max_digits=5, verbose_name='Porcentaje Ejecución Anterior')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecucion_porcentajes', to='proyectos.componente', verbose_name='Componente')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_construccion.regconstruccion', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Ejecución Porcentajes',
                'verbose_name_plural': 'Ejecuciones Porcentajes',
                'ordering': ['-fecha_calculo'],
                'unique_together': {('registro', 'componente')},
            },
        ),
        migrations.CreateModel(
            name='AvanceComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha del avance')),
                ('porcentaje_actual', models.IntegerField(default=0, help_text='Porcentaje de avance actual del componente (0-100)', verbose_name='Porcentaje actual')),
                ('porcentaje_acumulado', models.IntegerField(default=0, help_text='Porcentaje de avance acumulado del componente (0-100)', verbose_name='Porcentaje acumulado')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_componente', to='proyectos.componente', verbose_name='Componente')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_construccion.regconstruccion', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Avance por Componente',
                'verbose_name_plural': 'Avances por Componente',
                'ordering': ['-fecha', '-created_at'],
                'unique_together': {('registro', 'componente', 'fecha')},
            },
        ),
    ]
