# Generated by Django 5.2.3 on 2025-09-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_construccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancecomponente',
            name='porcentaje_actual',
            field=models.IntegerField(default=0, help_text='Porcentaje de avance actual del componente (0-100)', verbose_name='Porcentaje actual'),
        ),
        migrations.AddField(
            model_name='avancecomponente',
            name='porcentaje_acumulado',
            field=models.IntegerField(default=0, help_text='Porcentaje de avance acumulado del componente (0-100)', verbose_name='Porcentaje acumulado'),
        ),
        migrations.AddField(
            model_name='avancecomponente',
            name='porcentaje_anterior',
            field=models.IntegerField(default=0, help_text='Porcentaje de avance anterior del componente (0-100)', verbose_name='Porcentaje anterior'),
        ),
    ]
