# Generated by Django 5.2.3 on 2025-08-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_construccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceComponenteComentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_construccion.regconstruccion', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Comentarios Avance por Componente',
                'verbose_name_plural': 'Comentarios Avances por Componente',
            },
        ),
    ]
