# Generated by Django 5.2.3 on 2025-08-05 16:01

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('proyectos', '0001_initial'),
        ('reg_construccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalRegVisita',
            new_name='HistoricalRegConstruccion',
        ),
        migrations.RenameModel(
            old_name='RegVisita',
            new_name='RegConstruccion',
        ),
        migrations.AlterModelOptions(
            name='avance',
            options={'ordering': ['-fecha', '-created_at'], 'verbose_name': 'Registro Avance', 'verbose_name_plural': 'Registros Avance'},
        ),
        migrations.AlterModelOptions(
            name='historicalregconstruccion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical reg construccion', 'verbose_name_plural': 'historical reg construccions'},
        ),
        migrations.AddField(
            model_name='avance',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha del avance'),
        ),
        migrations.AddField(
            model_name='avance',
            name='porcentaje_avance',
            field=models.IntegerField(default=0, help_text='Porcentaje de avance del 0 al 100', verbose_name='Porcentaje de avance'),
        ),
    ]
