# Generated by Django 5.2.3 on 2025-01-27 10:30

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('reg_construccion', '0002_rename_historicalregvisita_historicalregconstruccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha del avance'),
        ),
        migrations.AddField(
            model_name='avance',
            name='porcentaje_avance',
            field=models.IntegerField(default=0, help_text='Porcentaje de avance del 0 al 100', verbose_name='Porcentaje de avance'),
        ),
    ]
