# Generated by Django 5.2.3 on 2025-08-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_construccion', '0002_avancecomponentecomentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='registro',
        ),
        migrations.DeleteModel(
            name='Avance',
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
    ]
