# Generated by Django 5.2.3 on 2025-08-05 16:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('reg_construccion', '0003_add_fecha_porcentaje_to_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha del avance')),
                ('porcentaje_actual', models.IntegerField(default=0, help_text='Porcentaje de avance actual del componente (0-100)', verbose_name='Porcentaje actual')),
                ('porcentaje_acumulado', models.IntegerField(default=0, help_text='Porcentaje de avance acumulado del componente (0-100)', verbose_name='Porcentaje acumulado')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_componente', to='proyectos.componente', verbose_name='Componente')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_construccion.regconstruccion', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Avance por Componente',
                'verbose_name_plural': 'Avances por Componente',
                'ordering': ['-fecha', '-created_at'],
                'unique_together': {('registro', 'componente', 'fecha')},
            },
        ),
    ]
