# Generated by Django 5.2.3 on 2025-08-12 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contratista'),
        ('reg_construccion', '0004_add_objetivo_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregconstruccion',
            name='contratista',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contratista', verbose_name='Contratista'),
        ),
        migrations.AddField(
            model_name='regconstruccion',
            name='contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_construccion', to='core.contratista', verbose_name='Contratista'),
        ),
    ]
