# Generated by Django 5.2.3 on 2025-08-05 19:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('reg_construccion', '0004_add_avance_componente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de ejecución')),
                ('ejecucion_anterior', models.IntegerField(default=0, help_text='Porcentaje de ejecución anterior del componente (0-100)', verbose_name='Ejecución anterior')),
                ('ejecucion_actual', models.IntegerField(default=0, help_text='Porcentaje de ejecución actual del componente (0-100)', verbose_name='Ejecución actual')),
                ('ejecucion_acumulada', models.IntegerField(default=0, help_text='Suma de ejecución anterior + actual (0-100)', verbose_name='Ejecución acumulada')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones_componente', to='proyectos.componente', verbose_name='Componente')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_construccion.regconstruccion', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Ejecución por Componente',
                'verbose_name_plural': 'Ejecuciones por Componente',
                'ordering': ['-fecha', '-created_at'],
                'unique_together': {('registro', 'componente', 'fecha')},
            },
        ),
    ]
