# Generated by Django 5.2.3 on 2025-08-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_construccion', '0005_historicalregconstruccion_contratista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregconstruccion',
            name='contratista',
        ),
        migrations.RemoveField(
            model_name='regconstruccion',
            name='contratista',
        ),
    ]
