# Generated by Django 5.2.3 on 2025-08-05 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('reg_construccion', '0005_ejecucioncomponente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionPorcentajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_ejec_actual', models.DecimalField(decimal_places=2, help_text='Porcentaje de ejecución actual del componente', max_digits=5, verbose_name='Porcentaje Ejecución Actual')),
                ('porcentaje_ejec_anterior', models.DecimalField(decimal_places=2, help_text='Porcentaje de ejecución anterior del componente', max_digits=5, verbose_name='Porcentaje Ejecución Anterior')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecucion_porcentajes', to='proyectos.componente', verbose_name='Componente')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_construccion.regconstruccion', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Ejecución Porcentajes',
                'verbose_name_plural': 'Ejecuciones Porcentajes',
                'ordering': ['-fecha_calculo'],
                'unique_together': {('registro', 'componente')},
            },
        ),
        migrations.DeleteModel(
            name='EjecucionComponente',
        ),
    ]
