# Generated by Django 5.2.3 on 2025-08-12 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_contratista_remove_contractor_address_and_more'),
        ('reg_construccion', '0006_remove_historicalregconstruccion_contratista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregconstruccion',
            name='contratista',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contractor', verbose_name='Contratista'),
        ),
        migrations.AddField(
            model_name='regconstruccion',
            name='contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_construccion', to='core.contractor', verbose_name='Contratista'),
        ),
    ]
