# Generated by Django 5.2.3 on 2025-08-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_construccion', '0007_historicalregconstruccion_contratista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregconstruccion',
            name='estado',
            field=models.CharField(choices=[('en_construccion', 'En Construcción'), ('paralizado', 'Paralizado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluido')], default='en_construccion', help_text='Estado actual del proyecto de construcción', max_length=20, verbose_name='Estado del Proyecto'),
        ),
        migrations.AddField(
            model_name='regconstruccion',
            name='estado',
            field=models.CharField(choices=[('en_construccion', 'En Construcción'), ('paralizado', 'Paralizado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluido')], default='en_construccion', help_text='Estado actual del proyecto de construcción', max_length=20, verbose_name='Estado del Proyecto'),
        ),
    ]
