# Generated by Django 5.2.3 on 2025-08-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_construccion', '0008_historicalregconstruccion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregconstruccion',
            name='estado',
            field=models.CharField(choices=[('construccion', 'Construcción'), ('paralizado', 'Paralizado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluido')], default='construccion', help_text='Estado actual del proyecto de construcción', max_length=20, verbose_name='Estado del Proyecto'),
        ),
        migrations.AlterField(
            model_name='regconstruccion',
            name='estado',
            field=models.CharField(choices=[('construccion', 'Construcción'), ('paralizado', 'Paralizado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluido')], default='construccion', help_text='Estado actual del proyecto de construcción', max_length=20, verbose_name='Estado del Proyecto'),
        ),
    ]
