# Generated by Django 5.2.4 on 2025-07-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rempalme',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='rsitio',
            name='registro',
        ),
        migrations.DeleteModel(
            name='RAcceso',
        ),
        migrations.DeleteModel(
            name='REmpalme',
        ),
        migrations.DeleteModel(
            name='RSitio',
        ),
    ]
