# Generated by Django 5.2.3 on 2025-07-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE registrostxtss_rsitio RENAME TO registros_rsitio;',
            reverse_sql='ALTER TABLE registros_rsitio RENAME TO registrostxtss_rsitio;',
        ),
    ]
