# Generated by Django 5.2.3 on 2025-07-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_rename_rsitio_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE registrostxtss_racceso RENAME TO registros_racceso;',
            reverse_sql='ALTER TABLE registros_racceso RENAME TO registrostxtss_racceso;',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE registrostxtss_rempalme RENAME TO registros_rempalme;',
            reverse_sql='ALTER TABLE registros_rempalme RENAME TO registrostxtss_rempalme;',
        ),
    ]
