# Generated by Django 5.2.3 on 2025-07-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_rename_all_tables'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS registrostxtss_registrostxtss;',
            reverse_sql='',  # No reverse operation since we're dropping the table
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS registrostxtss_mapasgoogle;',
            reverse_sql='',  # No reverse operation since we're dropping the table
        ),
    ]
