# Generated by Django 5.2.3 on 2025-07-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_rename_remaining_tables'),
    ]

    operations = [
        # First, drop the foreign key constraints
        migrations.RunSQL(
            sql='''
            PRAGMA foreign_keys=OFF;
            ''',
            reverse_sql='',
        ),
        # Drop the old tables
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS registrostxtss_registrostxtss;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS registrostxtss_mapasgoogle;',
            reverse_sql='',
        ),
        # Re-enable foreign keys
        migrations.RunSQL(
            sql='''
            PRAGMA foreign_keys=ON;
            ''',
            reverse_sql='',
        ),
    ]
