# Generated by Django 5.2.3 on 2025-07-07 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_historicalsite_user_site_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site', verbose_name='Sitio')),
            ],
            options={
                'verbose_name': 'Registro WOM',
                'verbose_name_plural': 'Registros WOM',
                'ordering': ['-created_at'],
            },
        ),
    ]
