# Generated by Django 5.2.3 on 2025-07-08 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalsite_user_site_user'),
        ('registrosWOM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro0', models.BooleanField(default=False, verbose_name='Registro 0')),
                ('registro1', models.BooleanField(default=False, verbose_name='Registro 1')),
                ('registro2', models.BooleanField(default=False, verbose_name='Registro 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site', verbose_name='Sitio')),
            ],
            options={
                'verbose_name': 'Registro WOM',
                'verbose_name_plural': 'Registros WOM',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Registros0',
        ),
    ]
