# Generated by Django 5.2.4 on 2025-07-19 14:45

import django.db.models.deletion
import registros.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registros', '0002_remove_rempalme_registro_remove_rsitio_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('acceso_sitio', models.TextField(max_length=100, verbose_name='Acceso al sitio')),
                ('acceso_sitio_construccion', models.TextField(max_length=100, verbose_name='Acceso al sitio para construcción')),
                ('longitud_acceso_sitio', models.IntegerField(verbose_name='Longitud acceso al Sitio')),
                ('longitud_acceso_construccion', models.IntegerField(verbose_name='Longitud acceso al Sitio para construcción')),
                ('tipo_suelo', models.CharField(max_length=100, verbose_name='Tipo de suelo de sitio y huella')),
                ('obstaculos', models.TextField(max_length=100, verbose_name='Edificaciones cercanas / obstáculos')),
                ('adicionales', models.TextField(blank=True, max_length=100, null=True, verbose_name='Trabajos adicionales a considerar')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.registros', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Registro Acceso',
                'verbose_name_plural': 'Registros Acceso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='REmpalme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(validators=[registros.models.validators.validar_latitud], verbose_name='Latitud Empalme')),
                ('lon', models.FloatField(validators=[registros.models.validators.validar_longitud], verbose_name='Longitud Empalme')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor de Energía')),
                ('capacidad', models.CharField(max_length=100, verbose_name='Capacidad de Energía')),
                ('no_poste', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Poste')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.registros', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Registro Empalme',
                'verbose_name_plural': 'Registros Empalme',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(validators=[registros.models.validators.validar_latitud], verbose_name='Latitud Inspeccion')),
                ('lon', models.FloatField(validators=[registros.models.validators.validar_longitud], verbose_name='Longitud Inspeccion')),
                ('altura', models.CharField(max_length=100, verbose_name='Altura Torre')),
                ('dimensiones', models.CharField(max_length=100)),
                ('deslindes', models.CharField(max_length=100)),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.registros', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Registro Sitio',
                'verbose_name_plural': 'Registros Sitio',
                'ordering': ['-created_at'],
            },
        ),
    ]
