# Generated by Django 5.2.4 on 2025-07-21 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros_txtss', '0001_initial'),
    ]

    operations = [
        # Agregar campos faltantes a Registros
        migrations.AddField(
            model_name='registros',
            name='title',
            field=models.CharField(default='Registro TX/TSS', max_length=100, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registros',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        
        # Agregar campos faltantes a RAcceso
        migrations.AddField(
            model_name='racceso',
            name='distancia',
            field=models.CharField(default='', max_length=100, verbose_name='Distancia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racceso',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
        
        # Eliminar campos obsoletos de RAcceso
        migrations.RemoveField(
            model_name='racceso',
            name='acceso_sitio',
        ),
        migrations.RemoveField(
            model_name='racceso',
            name='acceso_sitio_construccion',
        ),
        migrations.RemoveField(
            model_name='racceso',
            name='longitud_acceso_sitio',
        ),
        migrations.RemoveField(
            model_name='racceso',
            name='longitud_acceso_construccion',
        ),
        migrations.RemoveField(
            model_name='racceso',
            name='obstaculos',
        ),
        migrations.RemoveField(
            model_name='racceso',
            name='adicionales',
        ),
        
        # Eliminar campos obsoletos de REmpalme
        migrations.RemoveField(
            model_name='rempalme',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='rempalme',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='rempalme',
            name='no_poste',
        ),
        
        # Eliminar modelo MapasGoogle
        migrations.DeleteModel(
            name='MapasGoogle',
        ),
    ]
