# Generated by Django 5.2.4 on 2025-07-21 02:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appsettings'),
        ('registros_txtss', '0002_auto_20250721_0110'),
        ('users', '0002_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegistros',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical registros',
                'verbose_name_plural': 'historical registross',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='racceso',
            options={'verbose_name': 'Registro Acceso', 'verbose_name_plural': 'Registros Acceso'},
        ),
        migrations.AlterModelOptions(
            name='registros',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rempalme',
            options={'verbose_name': 'Registro Empalme', 'verbose_name_plural': 'Registros Empalme'},
        ),
        migrations.AlterModelOptions(
            name='rsitio',
            options={'verbose_name': 'Registro Sitio', 'verbose_name_plural': 'Registros Sitio'},
        ),
        migrations.RemoveConstraint(
            model_name='registros',
            name='unique_sitio_user_txtss_combination',
        ),
        migrations.AlterField(
            model_name='racceso',
            name='tipo_suelo',
            field=models.CharField(max_length=100, verbose_name='Tipo de Suelo'),
        ),
        migrations.AlterField(
            model_name='registros',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_txtss', to='core.site', verbose_name='Sitio'),
        ),
        migrations.AlterField(
            model_name='registros',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_txtss', to='users.user', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='rempalme',
            name='capacidad',
            field=models.CharField(max_length=100, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='rempalme',
            name='proveedor',
            field=models.CharField(max_length=100, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='historicalregistros',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalregistros',
            name='sitio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.site', verbose_name='Sitio'),
        ),
        migrations.AddField(
            model_name='historicalregistros',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user', verbose_name='Usuario'),
        ),
    ]
