# Generated by Django 5.2.3 on 2025-09-03 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('sitios_totales', 'Sitios Totales'), ('sitios_construccion', 'Sitios en Construcción'), ('sitios_paralizados', 'Sitios Paralizados'), ('sitios_concluidos', 'Sitios Concluidos'), ('registros_txtss', 'Registros TXTSS'), ('registros_construccion', 'Registros Construcción'), ('usuarios_activos', 'Usuarios Activos')], max_length=50, unique=True)),
                ('value', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica del Dashboard',
                'verbose_name_plural': 'Métricas del Dashboard',
            },
        ),
        migrations.CreateModel(
            name='SitioDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registros_txtss', models.IntegerField(default=0)),
                ('total_registros_construccion', models.IntegerField(default=0)),
                ('ultimo_registro_txtss', models.DateTimeField(blank=True, null=True)),
                ('ultimo_registro_construccion', models.DateTimeField(blank=True, null=True)),
                ('estado_actual', models.CharField(default='sin_estado', max_length=20)),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sitio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_info', to='core.site')),
            ],
            options={
                'verbose_name': 'Información de Sitio para Dashboard',
                'verbose_name_plural': 'Información de Sitios para Dashboard',
            },
        ),
    ]
