# Generated by Django 5.2.4 on 2025-07-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.registros'),
        ),
    ]
