# Generated by Django 5.2.3 on 2025-07-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='etapa',
            field=models.CharField(default='sitio', max_length=255),
            preserve_default=False,
        ),
    ]
