# Generated by Django 5.2.4 on 2025-07-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='app',
            field=models.CharField(default=1, max_length=100, verbose_name='Aplicación'),
            preserve_default=False,
        ),
    ]
