# Generated by Django 5.2.3 on 2025-07-19 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photos_etapa'),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.registros'),
        ),
    ]
