# Generated by Django 5.2.4 on 2025-07-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photos_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='deleted_at',
        ),
    ]
