# Generated by Django 5.2.3 on 2025-07-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photos_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
