# Generated by Django 5.2.4 on 2025-07-29 17:22

import datetime
import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('proyectos', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegVisita',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sitio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.site', verbose_name='Sitio')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical reg visita',
                'verbose_name_plural': 'historical reg visitas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RegVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site', verbose_name='Sitio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Usuario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvanceProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios adicionales sobre el avance del proyecto', null=True, verbose_name='Comentarios')),
                ('ejecucion_anterior', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de ejecución del período anterior', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Ejecución Anterior')),
                ('ejecucion_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de ejecución del período actual', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Ejecución Actual')),
                ('ejecucion_acumulada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de ejecución acumulada total', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Ejecución Acumulada')),
                ('ejecucion_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de ejecución total ponderado', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Ejecución Total')),
                ('componente', models.ForeignKey(blank=True, help_text='Componente específico del proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.componente', verbose_name='Componente')),
                ('proyecto', models.ForeignKey(blank=True, help_text='Seleccione la estructura de proyecto relacionado con esta visita', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.estructuraproyecto', verbose_name='Estructura Proyecto')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_visita.regvisita', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Avance de Proyecto',
                'verbose_name_plural': 'Avances de Proyecto',
                'ordering': ['-created_at'],
            },
        ),
    ]
