# Generated by Django 5.2.4 on 2025-07-25 13:01

from django.db import migrations


def populate_fecha(apps, schema_editor):
    """Poblar el campo fecha con la fecha de creación para registros existentes."""
    RegVisita = apps.get_model('reg_visita', 'RegVisita')
    for registro in RegVisita.objects.all():
        registro.fecha = registro.created_at.date()
        registro.save()


def reverse_populate_fecha(apps, schema_editor):
    """Operación inversa (no hace nada)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reg_visita', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE reg_visita_regvisita ADD COLUMN fecha DATE;',
            reverse_sql='ALTER TABLE reg_visita_regvisita DROP COLUMN fecha;'
        ),
        migrations.RunSQL(
            sql='ALTER TABLE reg_visita_historicalregvisita ADD COLUMN fecha DATE;',
            reverse_sql='ALTER TABLE reg_visita_historicalregvisita DROP COLUMN fecha;'
        ),
        migrations.RunPython(populate_fecha, reverse_populate_fecha),
    ]
