# Generated by Django 5.2.4 on 2025-07-25 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('reg_visita', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregvisita',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='regvisita',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_visita', to='core.site', verbose_name='Sitio'),
        ),
        migrations.AddField(
            model_name='regvisita',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_visita', to='users.user', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='avance',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_visita.regvisita', verbose_name='Registro'),
        ),
        migrations.AddField(
            model_name='visita',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_visita.regvisita', verbose_name='Registro'),
        ),
    ]
