# Generated by Django 5.2.4 on 2025-07-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_visita', '0002_initial'),
    ]

    operations = [
        # Corregir la restricción NOT NULL en created_at y updated_at de la tabla histórica para SQLite
        migrations.RunSQL(
            sql="""
            CREATE TABLE reg_visita_historicalregvisita_new (
                id bigint NOT NULL,
                created_at datetime NULL,
                updated_at datetime NULL,
                is_deleted bool NOT NULL,
                fecha date NOT NULL,
                is_active bool NOT NULL,
                title varchar(100) NOT NULL,
                description TEXT NULL,
                history_id INTEGER PRIMARY KEY AUTOINCREMENT,
                history_date datetime NOT NULL,
                history_change_reason varchar(100) NULL,
                history_type varchar(1) NOT NULL,
                history_user_id INTEGER NULL,
                sitio_id bigint NULL,
                user_id bigint NULL
            );
            INSERT INTO reg_visita_historicalregvisita_new 
            SELECT * FROM reg_visita_historicalregvisita;
            DROP TABLE reg_visita_historicalregvisita;
            ALTER TABLE reg_visita_historicalregvisita_new 
            RENAME TO reg_visita_historicalregvisita;
            """,
            reverse_sql="""
            CREATE TABLE reg_visita_historicalregvisita_old (
                id bigint NOT NULL,
                created_at datetime NOT NULL,
                updated_at datetime NOT NULL,
                is_deleted bool NOT NULL,
                fecha date NOT NULL,
                is_active bool NOT NULL,
                title varchar(100) NOT NULL,
                description TEXT NULL,
                history_id INTEGER PRIMARY KEY AUTOINCREMENT,
                history_date datetime NOT NULL,
                history_change_reason varchar(100) NULL,
                history_type varchar(1) NOT NULL,
                history_user_id INTEGER NULL,
                sitio_id bigint NULL,
                user_id bigint NULL
            );
            INSERT INTO reg_visita_historicalregvisita_old 
            SELECT * FROM reg_visita_historicalregvisita;
            DROP TABLE reg_visita_historicalregvisita;
            ALTER TABLE reg_visita_historicalregvisita_old 
            RENAME TO reg_visita_historicalregvisita;
            """
        ),
    ]
