# Generated by Django 5.2.3 on 2025-08-04 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('reg_visita', '0003_auto_20250725_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregvisita',
            name='grupo_actividades',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Grupo de actividades asociado a este registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyectos.grupo', verbose_name='Grupo de Actividades'),
        ),
        migrations.AddField(
            model_name='regvisita',
            name='grupo_actividades',
            field=models.ForeignKey(blank=True, help_text='Grupo de actividades asociado a este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.grupo', verbose_name='Grupo de Actividades'),
        ),
    ]
