# Generated by Django 5.2.3 on 2025-08-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_visita', '0004_historicalregvisita_grupo_actividades_and_more'),
    ]

    operations = [
    ]
