# Generated by Django 5.2.3 on 2025-08-04 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('reg_visita', '0005_auto_20250804_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregvisita',
            name='grupo_actividades',
        ),
        migrations.RemoveField(
            model_name='regvisita',
            name='grupo_actividades',
        ),
        migrations.AddField(
            model_name='historicalregvisita',
            name='estructura',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proyectos.grupo', verbose_name='Estructura'),
        ),
        migrations.AddField(
            model_name='regvisita',
            name='estructura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_visita', to='proyectos.grupo', verbose_name='Estructura'),
        ),
    ]
