# Generated by Django 5.2.3 on 2025-07-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_site_options_remove_historicalsite_user_and_more'),
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrosTxTss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro0', models.BooleanField(default=False, verbose_name='Registro 0')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site', verbose_name='Sitio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro Tx/Tss',
                'verbose_name_plural': 'Registros Tx/Tss',
                'ordering': ['-created_at'],
            },
        ),
    ]
