# Generated by Django 5.2.3 on 2025-07-09 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_site_options_remove_historicalsite_user_and_more'),
        ('registrostxtss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrostxtss',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site', unique=True, verbose_name='Sitio'),
        ),
    ]
