# Generated by Django 5.2.3 on 2025-07-09 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_site_options_remove_historicalsite_user_and_more'),
        ('registrostxtss', '0004_registrostxtss_unique_user_with_registro0_true'),
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registrostxtss',
            name='unique_user_with_registro0_true',
        ),
        migrations.AlterField(
            model_name='registrostxtss',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site', verbose_name='Sitio'),
        ),
        migrations.AddConstraint(
            model_name='registrostxtss',
            constraint=models.UniqueConstraint(condition=models.Q(('registro0', True)), fields=('sitio',), name='unique_sitio_with_registro0_true'),
        ),
    ]
