# Generated by Django 5.2.3 on 2025-07-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0007_fix_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrostxtss',
            name='registro0',
        ),
        migrations.AddField(
            model_name='registrostxtss',
            name='registro',
            field=models.BooleanField(default=False, verbose_name='Registro'),
        ),
    ]
