# Generated by Django 5.2.3 on 2025-07-10 15:26

import django.db.models.deletion
import registrostxtss.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0008_remove_registrostxtss_registro0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registros0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(validators=[registrostxtss.models.validators.validar_latitud], verbose_name='Latitud Inspeccion')),
                ('lon', models.FloatField(validators=[registrostxtss.models.validators.validar_longitud], verbose_name='Longitud Inspeccion')),
                ('altura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Altura (m)')),
                ('dimensiones', models.CharField(max_length=100, null=True)),
                ('deslindes', models.CharField(max_length=100, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrostxtss.registrostxtss', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Registro 0',
                'verbose_name_plural': 'Registros 0',
                'ordering': ['-created_at'],
            },
        ),
    ]
