# Generated by Django 5.2.3 on 2025-07-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0009_registros1_registros0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros0',
            name='deslindes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registros0',
            name='dimensiones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
