# Generated by Django 5.2.3 on 2025-07-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0010_alter_registros0_deslindes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros0',
            name='altura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Altura Torre'),
        ),
    ]
