# Generated by Django 5.2.3 on 2025-07-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0011_alter_registros0_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros0',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
    ]
