# Generated by Django 5.2.3 on 2025-07-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0013_alter_registros0_altura_alter_registros0_deslindes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrostxtss',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrostxtss',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrostxtss',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registrostxtss',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
