# Generated by Django 5.2.3 on 2025-07-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0014_registrostxtss_deleted_at_registrostxtss_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrostxtss',
            name='registro',
        ),
        migrations.AlterField(
            model_name='registrostxtss',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Registro'),
        ),
    ]
