# Generated by Django 5.2.3 on 2025-07-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0015_remove_registrostxtss_registro_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registros0',
            new_name='RSitio',
        ),
        migrations.AlterModelOptions(
            name='rsitio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Registro Sitio', 'verbose_name_plural': 'Registros Sitio'},
        ),
    ]
