# Generated by Django 5.2.3 on 2025-07-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0016_rename_registros0_rsitio_alter_rsitio_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registros1',
        ),
    ]
