# Generated by Django 5.2.3 on 2025-07-14 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0017_delete_registros1'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('acceso_sitio', models.TextField(max_length=100, verbose_name='Acceso al sitio')),
                ('acceso_sitio_construccion', models.TextField(max_length=100, verbose_name='Acceso al sitio para construcción')),
                ('longitud_acceso_sitio', models.IntegerField(verbose_name='Longitud acceso al Sitio')),
                ('longitud_acceso_construccion', models.IntegerField(verbose_name='Longitud acceso al Sitio para construcción')),
                ('tipo_suelo', models.CharField(max_length=100, verbose_name='Tipo de suelo de sitio y huella')),
                ('obstaculos', models.TextField(max_length=100, verbose_name='Edificaciones cercanas / obstáculos')),
                ('adicionales', models.TextField(max_length=100, verbose_name='Trabajos adicionales a considerar')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrostxtss.registrostxtss', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Registro Acceso',
                'verbose_name_plural': 'Registros Acceso',
                'ordering': ['-created_at'],
            },
        ),
    ]
