# Generated by Django 5.2.3 on 2025-07-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0018_racceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racceso',
            name='adicionales',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Trabajos adicionales a considerar'),
        ),
    ]
