# Generated by Django 5.2.3 on 2025-07-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0020_rempalme'),
    ]

    operations = [
        migrations.AddField(
            model_name='rempalme',
            name='no_poste',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Poste'),
        ),
    ]
