# Generated by Django 5.2.3 on 2025-07-18 03:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0021_rempalme_no_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaDesfase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='mapas_desfase/')),
                ('desfase_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coordenadas_mandato', models.JSONField(blank=True, null=True)),
                ('coordenadas_inspeccion', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapas_desfase', to='registrostxtss.registrostxtss')),
            ],
            options={
                'verbose_name': 'Mapa de Desfase',
                'verbose_name_plural': 'Mapas de Desfase',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
