# Generated by Django 5.2.3 on 2025-07-18 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0022_mapadesfase'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapasGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=100, verbose_name='Etapa')),
                ('archivo', models.FileField(upload_to='rsitio/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapas_desfase', to='registrostxtss.registrostxtss')),
            ],
            options={
                'verbose_name': 'Mapa Google',
                'verbose_name_plural': 'Mapas Google',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='MapaDesfase',
        ),
    ]
