# Generated by Django 5.2.3 on 2025-07-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0023_mapasgoogle_delete_mapadesfase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapasgoogle',
            name='archivo',
            field=models.FileField(upload_to='google_maps/'),
        ),
        migrations.AddConstraint(
            model_name='mapasgoogle',
            constraint=models.UniqueConstraint(fields=('registro', 'etapa'), name='unique_registro_etapa_combination'),
        ),
    ]
