# Generated by Django 5.2.3 on 2025-07-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrostxtss', '0024_alter_mapasgoogle_archivo_and_more'),
        ('registrostxtss', '0024_cleanup_mapasgoogle_duplicates'),
    ]

    operations = [
    ]
