# Generated by Django 5.2.3 on 2025-07-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenes',
            options={'ordering': ['orden', '-created_at'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AddField(
            model_name='imagenes',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
